[project]
name = "attendance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "reportlab>=4.4.4",
    "reportlib>=3.4.0",
    "xlrd>=2.0.2",
]
